### ISSUE TITLE
Using in a stand alone window manager like xmonad

### ISSUE THREAD

**Issue by 0xadeeb** [nicolabaesso/GalaxyDebianRedSplashScreen#1]
Can this be used in sddm without plasma plugins. If so please explain how?

**Comment by nicolabaesso** [comment]
Hi, not in a way that I'm aware of.
This splashscreen (and the others I made) won't run outside Plasma.

For example, if you run i3 after the login, it won't load this splashscreen.

I will re-open this issue if I find a way.
